# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Itonics < Formula
  desc "Command-line client for the ITONICS Innovation OData v2 API"
  homepage "https://github.com/itonics/itonics-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itonics/itonics-cli/releases/download/v0.1.0/itonics_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "cae5c8970960c6cec71bcf9d8ae4758660b85e4e9b3dfc22f271a189ed811983"

      define_method(:install) do
        bin.install "itonics"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itonics/itonics-cli/releases/download/v0.1.0/itonics_0.1.0_Darwin_arm64.tar.gz"
      sha256 "58a62fe44ecb9029e86fdbc2444e7b59fde9dfd023d3c6e1bf1800155513c393"

      define_method(:install) do
        bin.install "itonics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itonics/itonics-cli/releases/download/v0.1.0/itonics_0.1.0_Linux_x86_64.tar.gz"
      sha256 "7341bcd112566a2130fbd5050c269bfad9894878e73085f85a291582a0e8c176"
      define_method(:install) do
        bin.install "itonics"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itonics/itonics-cli/releases/download/v0.1.0/itonics_0.1.0_Linux_arm64.tar.gz"
      sha256 "16bff9ee57865a9935d5b1af603d04849ac1e720811e5da507840040d546920f"
      define_method(:install) do
        bin.install "itonics"
      end
    end
  end

  test do
    assert_match "itonics", shell_output("#{bin}/itonics --help")
    assert_match "elements", shell_output("#{bin}/itonics --help")
  end
end
