# This formula is regenerated by goreleaser on every release.
#
# Initial seed only: real `url` and `sha256` values are written by the
# `brews:` block in .goreleaser.yaml after the first `v*` tag is pushed.
# Until then, install with `brew install --HEAD ./Formula/itonics.rb` or
# build from source with `go install`.
class Itonics < Formula
  desc "Command-line client for the ITONICS Innovation OData v2 API"
  homepage "https://github.com/itonics/itonics-cli"
  version "0.0.0"
  license "MIT"

  head "https://github.com/itonics/itonics-cli.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build",
           "-ldflags", "-s -w -X github.com/itonics/itonics-cli/cmd.Version=#{version}",
           "-o", bin/"itonics", "./"
  end

  test do
    assert_match "itonics", shell_output("#{bin}/itonics --help")
    assert_match "elements", shell_output("#{bin}/itonics --help")
  end
end
